baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'raflyadek'
relativeURLs = true
disableFastRender = true
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

[params]
    dateFormat = "Jan 2, 2006"

